DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  first_name VARCHAR(255)
);

CREATE TABLE couches (
  id INT PRIMARY KEY AUTO_INCREMENT,
  material VARCHAR(255) NOT NULL,
  color VARCHAR(255) NOT NULL,
  condition VARCHAR(255) NOT NULL,
  age INT
);